import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import AppLayout from "./components/layout/AppLayout";
import { SnackbarProvider } from "./context/SnackbarContext";
import { CommonProvider } from "./context/CommonProvider";
import { MUIProvider } from "./context/MUIProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MUIProvider>
          <SnackbarProvider>
            <CommonProvider>
              <AppLayout>
                {children}
              </AppLayout>
            </CommonProvider>
          </SnackbarProvider>
        </MUIProvider>
      </body>
    </html>
  );
}
